In [3]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

1

In [5]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2

In [6]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]], float)
B = np.array([1, 7, 12, 7, 15])  
np.linalg.lstsq(A, B)[0]

<ipython-input-6-bfb00354d6e2>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)[0]


array([ 1.13919353, -0.90498444, -0.9009803 ])

4

In [7]:
A = np.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
L = np.array([ [1, 0, 0], [0.25, 1, 0], [0.5, -0.4, 1]])
U = np.array([ [4, 28, 73], [0, -5, -15.25], [0, 0, -21.6]])
A = np.dot(L, U)
P, L, U = scipy.linalg.lu(A)

print("det A = ", np.linalg.det(A))
print("A = ", A)
print("P = ", P)
print("L = ", L)
print("U = ", U)

B = np.array([4, 1, 7])
np.linalg.solve(A, B)

det A =  432.00000000000017
A =  [[ 4. 28. 73.]
 [ 1.  2.  3.]
 [ 2. 16. 21.]]
P =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L =  [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U =  [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


array([ 0.28240741,  0.70601852, -0.23148148])

7

In [9]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)
 
print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [10]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -5.26517217e-16 -2.55176183e-16]
 [-5.26517217e-16  1.00000000e+00  3.37757775e-16]
 [-2.55176183e-16  3.37757775e-16  1.00000000e+00]]


In [11]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [12]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [13]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 9.45096256e-15])

In [14]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 9.45096256e-15 0.00000000e+00]


1.4999999999999893

In [15]:
np.linalg.norm(np.dot(A, X) - B)

1.2247448713915885

In [16]:
X = np.array([1.5, 1, 0.5])
np.linalg.norm(X),  np.linalg.norm(np.dot(A, X) - B)

(1.8708286933869707, 15.297058540778355)